# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: 'pixiprototype'
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: 'pixiprototype'
            customCommand: 'run build:prod --prod'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'pixiprototype/dist'
            ArtifactName: 'pixiprototype'
            publishLocation: 'Container'
- stage: deploy_dev
  displayName: Deploy to development
  variables:
  - group: DEV
  jobs:
    - deployment: DeployWeb
      environment: DEV
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, development world!
